//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStoreDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ask_qustion
    {
        public int qus_id { get; set; }
        public string qus_text { get; set; }
        public int p_id { get; set; }
        public System.DateTime date { get; set; }
        public string c_email { get; set; }
    
        public virtual product product { get; set; }
    }
}
